index:
    path: /{vueRouter}
    controller: App\Controller\DefaultController::index
    defaults: {vueRouter: '/'}
    requirements:
        vueRouter: ^(?!api|_(profiler|wdt)).*

import.new:
    path: import/new
    controller: App\Controller\ImportController::newImport

